language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO=Django==1.4.5
  - DJANGO=Django==1.5.8
  - DJANGO=Django==1.6.7
  - DJANGO=Django==1.7

install:
  - pip install -q $DJANGO

script:
  - PYTHONPATH=$PYTHONPATH:$PWD django-admin.py test adminrestrict

matrix:
    exclude:
        - python: 3.3
          env: DJANGO=Django==1.4.5
